---
collections:

dependencies:
  - role: base
  - role: leonardehrenfried.baseline.send_to_matrix
  - role: leonardehrenfried.baseline.podman
  - role: leonardehrenfried.baseline.caddyfile
  - role: leonardehrenfried.baseline.otp_restart
  - role: leonardehrenfried.baseline.send_to_matrix
